const OPTIMISATION_RUN_STATUS = Object.freeze({
  PROCESSING: 'PROCESSING',
  ABORTING: 'ABORTING',
  PROCESSED: 'PROCESSED',
  FAILED: 'FAILED',
  ABORTED: 'ABORTED',
});

export default OPTIMISATION_RUN_STATUS;
